**[Pandas Home Page](https://www.kaggle.com/learn/pandas)**

---

# Introduction

In these exercises we'll apply groupwise analysis to our dataset.

Run the code cell below to load the data before running the exercises.

In [1]:
import pandas as pd

reviews = pd.read_csv("../input/wine-reviews/winemag-data-130k-v2.csv", index_col=0)
#pd.set_option("display.max_rows", 5)

from learntools.core import binder; binder.bind(globals())
from learntools.pandas.grouping_and_sorting import *
print("Setup complete.")

Setup complete.

# Tutorial

## Groupwise analysis
One function we've been using heavily thus far is the value_counts() function. We can replicate what value_counts() does by doing the following:

In [3]:
reviews.groupby('points').points.count()

points
80       397
81       692
82      1836
83      3025
84      6480
85      9530
86     12600
87     16933
88     17207
89     12226
90     15410
91     11359
92      9613
93      6489
94      3758
95      1535
96       523
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [ ]:
reviews.groupby('points').points.count()

groupby() created a group of reviews which allotted the same point values to the given wines. Then, for each of these groups, we grabbed the points() column and counted how many times it appeared. value_counts() is just a shortcut to this groupby() operation.

We can use any of the summary functions we've used before with this data. For example, to get the cheapest wine in each point value category, we can do the following:

In [5]:
reviews.points.value_counts()

88     17207
87     16933
90     15410
86     12600
89     12226
91     11359
92      9613
85      9530
93      6489
84      6480
94      3758
83      3025
82      1836
95      1535
81       692
96       523
80       397
97       229
98        77
99        33
100       19
Name: points, dtype: int64

In [20]:
# print cheapest wine in each point value category

reviews.groupby('points')['price'].min()

points
80      5.0
81      5.0
82      4.0
83      4.0
84      4.0
85      4.0
86      4.0
87      5.0
88      6.0
89      7.0
90      8.0
91      7.0
92     11.0
93     12.0
94     13.0
95     20.0
96     20.0
97     35.0
98     50.0
99     44.0
100    80.0
Name: price, dtype: float64

You can think of each group we generate as being a slice of our DataFrame containing only data with values that match.<br>

The DataFrame is accessible to us directly using the <code>apply()</code> mehtod, and we can then manipulate the data in any way we see fit.

Fore example, here's one way of selecting the name of the first wine reviewed from each winery in the dataset

*How can we do that?*

In [22]:
reviews.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

In [25]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
1+1=3                                     1+1=3 NV Rosé Sparkling (Cava)
10 Knots                            10 Knots 2010 Viognier (Paso Robles)
100 Percent Wine              100 Percent Wine 2015 Moscato (California)
1000 Stories           1000 Stories 2013 Bourbon Barrel Aged Zinfande...
1070 Green                  1070 Green 2011 Sauvignon Blanc (Rutherford)
                                             ...
Órale                       Órale 2011 Cabronita Red (Santa Ynez Valley)
Öko                    Öko 2013 Made With Organically Grown Grapes Ma...
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Štoka                                    Štoka 2009 Izbrani Teran (Kras)
Length: 16757, dtype: object

Q1. 국가, 지역별 가장 높은 point를 얻은 와인 뽑아내기<br>
일상속에서 많이 접할 수 있는 문제인 것 같다

For more fine-grained control, we can also group by more than one column

In [32]:
reviews.groupby('country').apply(lambda df: df.loc[df.points.idxmax()])

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
country,,,,,,,,,,,,,
Argentina,Argentina,"If the color doesn't tell the full story, the ...",Nicasia Vineyard,97,120.0,Mendoza Province,Mendoza,NaN,Michael Schachner,@wineschach,Bodega Catena Zapata 2006 Nicasia Vineyard Mal...,Malbec,Bodega Catena Zapata
Armenia,Armenia,"Deep salmon in color, this wine offers a bouqu...",Estate Bottled,88,15.0,Armenia,NaN,NaN,Mike DeSimone,@worldwineguys,Van Ardi 2015 Estate Bottled Rosé (Armenia),Rosé,Van Ardi
Australia,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
Austria,Austria,Opulent honey and lemon aromas waft from the g...,Zwischen den Seen Nummer 9 Trockenbeerenauslese,98,NaN,Burgenland,NaN,NaN,Roger Voss,@vossroger,Kracher 2008 Zwischen den Seen Nummer 9 Trocke...,Welschriesling,Kracher
Bosnia and Herzegovina,Bosnia and Herzegovina,A mix of red and black fruits pervade on the n...,NaN,88,12.0,Mostar,NaN,NaN,Jeff Jenssen,@worldwineguys,Winery Čitluk 2011 Blatina (Mostar),Blatina,Winery Čitluk
Brazil,Brazil,Stony polished white-fruit aromas are lean and...,Brut Nature,89,36.0,Pinto Bandeira,NaN,NaN,Michael Schachner,@wineschach,Cave Geisse 2013 Brut Nature Sparkling (Pinto ...,Sparkling Blend,Cave Geisse
Bulgaria,Bulgaria,This Bulgarian red blend is produced under the...,CR,91,30.0,Thracian Valley,NaN,NaN,Jeff Jenssen,@worldwineguys,Castra Rubra 2010 CR Red (Thracian Valley),Bordeaux-style Red Blend,Castra Rubra
Canada,Canada,"Smooth as silk and deeply concentrated, this o...",Riesling Icewine,94,60.0,Ontario,Niagara Peninsula,NaN,Paul Gregutt,@paulgwine,Cave Spring 2013 Riesling Icewine Riesling (Ni...,Riesling,Cave Spring
Chile,Chile,"Clos Apalta, depending on your point of view, ...",Clos Apalta,95,90.0,Colchagua Valley,NaN,NaN,Michael Schachner,@wineschach,Lapostolle 2008 Clos Apalta Red (Colchagua Val...,Red Blend,Lapostolle
China,China,This deep ruby-colored wine features a bouquet...,Noble Dragon,89,18.0,China,NaN,NaN,Mike DeSimone,@worldwineguys,Chateau Changyu-Castel 2009 Noble Dragon Red (...,Cabernet Blend,Chateau Changyu-Castel
Croatia,Croatia,This 100% Teran from Istria has aromas of blue...,Terra Mare,91,33.0,Istria,NaN,NaN,Jeff Jenssen,@worldwineguys,Trapan 2013 Terra Mare Teran (Istria),Teran,Trapan
Cyprus,Cyprus,This Cretan indigenous white offers aromas of ...,NaN,89,21.0,Lemesos,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsiakkas 2014 Xynisteri (Lemesos),Xynisteri,Tsiakkas
Czech Republic,Czech Republic,"This red blend has a nose of fresh cherry, red...",Roucí,89,45.0,Moravia,NaN,NaN,Jeff Jenssen,@worldwineguys,Stapleton & Springer 2007 Roucí Red (Moravia),Red Blend,Stapleton & Springer
Egypt,Egypt,"Ripe pear, apple and tropical fruit in the nos...",Caspar Blanc de Noirs,84,NaN,Egypt,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Sahara Vineyards 2008 Caspar Blanc de Noirs Gr...,Grenache,Sahara Vineyards
England,England,"Touches of vanilla, cream and lovely hints of ...",Blanc de Blancs,95,70.0,England,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Nyetimber 2010 Blanc de Blancs Chardonnay (Eng...,Chardonnay,Nyetimber
France,France,This is a fabulous wine from the greatest Cham...,Brut,100,259.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Krug 2002 Brut (Champagne),Champagne Blend,Krug
Georgia,Georgia,"From it's musky, perfumed to nose to it's inte...",Qvevri Traditional Kakhuri Dry Unfiltered Ambe...,92,25.0,Kakheti,NaN,NaN,Anna Lee C. Iijima,NaN,Alaverdi Monastery Cellar 2010 Qvevri Traditio...,Rkatsiteli,Alaverdi Monastery Cellar
Germany,Germany,"With layers upon layers of spicy saffron, peac...",Kiedrich Gräfenberg Trockenbeerenauslese,98,775.0,Rheingau,NaN,NaN,Anna Lee C. Iijima,NaN,Robert Weil 2015 Kiedrich Gräfenberg Trockenbe...,Riesling,Robert Weil
Greece,Greece,"Vanilla, citrus and white flowers on the nose ...",NaN,93,16.0,Mantinia,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Dionysos 2014 Moschofilero (Mantinia),Moschofilero,Dionysos
Hungary,Hungary,"This ethereal Tokaji Aszú is golden in color, ...",6 Puttonyos Aszú Gold Label,97,80.0,Tokaji,NaN,NaN,Jeff Jenssen,@worldwineguys,Royal Tokaji 2013 6 Puttonyos Aszú Gold Label ...,White Blend,Royal Tokaji
India,India,"The nose carries notes of cassis, blackberry a...",Dindori Reserve,93,20.0,Nashik,NaN,NaN,Mike DeSimone,@worldwineguys,Sula 2011 Dindori Reserve Shiraz (Nashik),Shiraz,Sula
Israel,Israel,"Inky red-violet to the eye, this wine has an i...",Reserve David Vineyard,94,25.0,Galilee,NaN,NaN,Mike DeSimone,@worldwineguys,Recanati 2011 Reserve David Vineyard Cabernet ...,Cabernet Sauvignon,Recanati
Italy,Italy,Thick as molasses and dark as caramelized brow...,Occhio di Pernice,100,210.0,Tuscany,Vin Santo di Montepulciano,NaN,NaN,NaN,Avignonesi 1995 Occhio di Pernice (Vin Santo ...,Prugnolo Gentile,Avignonesi
Lebanon,Lebanon,"Violet red to the eye, this wine is a blend of...",El,91,75.0,Lebanon,NaN,NaN,Mike DeSimone,@worldwineguys,Ixsir 2011 El Red (Lebanon),Red Blend,Ixsir
Luxembourg,Luxembourg,"Made from Auxerrois, this delightful white has...",Bech-Kleinmacher Naumberg Grand Premier Cru,90,22.0,Moselle Luxembourgeoise,NaN,NaN,Jeff Jenssen,@worldwineguys,Domaines Vinsmoselle 2014 Bech-Kleinmacher Nau...,Auxerrois,Domaines Vinsmoselle
Macedonia,Macedonia,This 100% Vranec presents the nose with black ...,Veritas,89,20.0,Tikves,NaN,NaN,Jeff Jenssen,@worldwineguys,Stobi 2011 Veritas Vranec (Tikves),Vranec,Stobi
Mexico,Mexico,"A world-class wine regardless of origin, this ...",Amado IV,92,54.0,Valle de Guadalupe,NaN,NaN,Michael Schachner,@wineschach,Viñas de Garza 2007 Amado IV Red (Valle de Gua...,Red Blend,Viñas de Garza
Moldova,Moldova,"Bright ruby in the glass, this wine is a blend...",Freedom Blend,91,25.0,Moldova,NaN,NaN,Jeff Jenssen,@worldwineguys,Purcari 2013 Freedom Blend Red (Moldova),Red Blend,Purcari
Morocco,Morocco,"Aromas of black cherry, espresso bean and whit...",Médaillon,93,18.0,Zenata,NaN,NaN,Mike DeSimone,@worldwineguys,Ouled Thaleb 2012 Médaillon Red (Zenata),Red Blend,Ouled Thaleb
New Zealand,New Zealand,"This full-bodied, richly tannic wine delivers....",Homage,95,100.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Trinity Hill 2013 Homage Syrah (Hawke's Bay),Syrah,Trinity Hill
Peru,Peru,"Earthy, warm and ripe on the bouquet, with a b...",Sinfonía Tannat-Malbec-Petit Verdot,86,20.0,Ica,NaN,NaN,Michael Schachner,@wineschach,Tacama 2008 Sinfonía Tannat-Malbec-Petit Verdo...,Red Blend,Tacama
Portugal,Portugal,This is the latest release of what has long be...,Barca-Velha,100,450.0,Douro,NaN,NaN,Roger Voss,@vossroger,Casa Ferreirinha 2008 Barca-Velha Red (Douro),Portuguese Red,Casa Ferreirinha
Romania,Romania,This late harvest Sauvignon Blanc is honey gol...,Conocul Ambrozy,92,28.0,Recas,NaN,NaN,Jeff Jenssen,@worldwineguys,Cramele Recas 2013 Conocul Ambrozy Sauvignon B...,Sauvignon Blanc,Cramele Recas
Serbia,Serbia,A blend of 60% Prokupac and 40% Cabernet Sauvi...,Sub Rosa,89,40.0,Župa,NaN,NaN,Jeff Jenssen,@worldwineguys,Budimir 2009 Sub Rosa Red (Župa),Red Blend,Budimir
Slovakia,Slovakia,"Delicious scents of honey, apples and petrol l...",NaN,87,16.0,Muzla,NaN,NaN,Anna Lee C. Iijima,NaN,Château Bela 2008 Riesling (Muzla),Riesling,Château Bela
Slovenia,Slovenia,"This has ebullient aromas of cherry blossom, g...",Veliko,92,50.0,Brda,NaN,NaN,Anna Lee C. Iijima,NaN,Movia 2007 Veliko White (Brda),White Blend,Movia
South Africa,South Africa,Only 95 cases were made of this Bordeaux-style...,Book 17 XVII,95,330.0,Stellenbosch,NaN,NaN,Lauren Buzzeo,@laurbuzz,De Toren 2014 Book 17 XVII Red (Stellenbosch),Bordeaux-style Red Blend,De Toren
Spain,Spain,Luscious prune and blackberry aromas come with...,Clon de la Familia,98,450.0,Northern Spain,Ribera del Duero,NaN,Michael Schachner,@wineschach,Emilio Moro 2009 Clon de la Familia (Ribera d...,Tinto Fino,Emilio Moro
Switzerland,Switzerland,"A Swiss blend of Pinot Noir and Gamay, this de...",Dôle des Monts,90,30.0,Valais,NaN,NaN,Jeff Jenssen,@worldwineguys,Robert Gilliard 2012 Dôle des Monts Pinot Noir...,Pinot Noir-Gamay,Robert Gilliard
Turkey,Turkey,"Aromas of black cherry, brambly berry, violet ...",Pendore,92,38.0,Aegean,NaN,NaN,Mike DeSimone,@worldwineguys,Kavaklidere 2010 Pendore Syrah (Aegean),Syrah,Kavaklidere
US,US,Tasted in a flight of great and famous Napa wi...,NaN,100,200.0,California,Napa Valley,Napa,NaN,NaN,Cardinale 2006 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Cardinale
Ukraine,Ukraine,"This has aromas of white flowers, especially h...",Reserve,88,9.0,Ukraine,NaN,NaN,Jeff Jenssen,@worldwineguys,Koblevo NV Reserve Riesling (Ukraine),Riesling,Koblevo
Uruguay,Uruguay,Dried blackberry aromas include welcome notes ...,B6 Parcela Única,92,43.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Bouza 2015 B6 Parcela Única Tannat (Canelones),Tannat,Bouza

In [34]:
reviews.groupby(['country', 'province']).apply(lambda df: df.loc[df.points.idxmax()])

                              country  \
country   province
Argentina Mendoza Province  Argentina
          Other             Argentina
Armenia   Armenia             Armenia
Australia Australia Other   Australia
          New South Wales   Australia
...                               ...
Uruguay   Juanico             Uruguay
          Montevideo          Uruguay
          Progreso            Uruguay
          San Jose            Uruguay
          Uruguay             Uruguay

                                                                  description  \
country   province
Argentina Mendoza Province  If the color doesn't tell the full story, the ...
          Other             Take note, this could be the best wine Colomé ...
Armenia   Armenia           Deep salmon in color, this wine offers a bouqu...
Australia Australia Other   Writes the book on how to make a wine filled w...
          New South Wales   De Bortoli's Noble One is as good as ever in 2...
...                                                                       ...
Uruguay   Juanico           This mature Bordeaux-style blend is earthy on ...
          Montevideo        A rich, heady bouquet offers aromas of blackbe...
          Progreso          Rusty in color but deep and complex in nature,...
          San Jose          Baked, sweet, heavy aromas turn earthy with ti...
          Uruguay           Cherry and berry aromas are ripe, healthy and ...

                                                        designation  points  \
country   province
Argentina Mendoza Province                         Nicasia Vineyard      97
          Other                                             Reserva      95
Armenia   Armenia                                    Estate Bottled      88
Australia Australia Other                             Sarah's Blend      93
          New South Wales                        Noble One Bortytis      94
...                                                             ...     ...
Uruguay   Juanico                  Preludio Barrel Select Lote N 77      90
          Montevideo        Monte Vide Eu Tannat-Merlot-Tempranillo      91
          Progreso                   Etxe Oneko Fortified Sweet Red      90
          San Jose                         El Preciado Gran Reserva      87
          Uruguay                         Blend 002 Limited Edition      91

                            price          province                 region_1  \
country   province
Argentina Mendoza Province  120.0  Mendoza Province                  Mendoza
          Other              90.0             Other                    Salta
Armenia   Armenia            15.0           Armenia                      NaN
Australia Australia Other    15.0   Australia Other  South Eastern Australia
          New South Wales    32.0   New South Wales          New South Wales
...                           ...               ...                      ...
Uruguay   Juanico            45.0           Juanico                      NaN
          Montevideo         60.0        Montevideo                      NaN
          Progreso           46.0          Progreso                      NaN
          San Jose           50.0          San Jose                      NaN
          Uruguay            22.0           Uruguay                      NaN

                           region_2        taster_name taster_twitter_handle  \
country   province
Argentina Mendoza Province      NaN  Michael Schachner           @wineschach
          Other                 NaN  Michael Schachner           @wineschach
Armenia   Armenia               NaN      Mike DeSimone        @worldwineguys
Australia Australia Other       NaN                NaN                   NaN
          New South Wales       NaN     Joe Czerwinski                @JoeCz
...                             ...                ...                   ...
Uruguay   Juanico               NaN  Michael Schachner           @wineschach
          Montevideo            NaN  Michael Schachner           @wineschach
          Progreso              NaN  Michael Schachner           @wineschach
          San Jose              NaN  Michael Schachner           @wineschach
          Uruguay               NaN  Michael Schachner           @wineschach

                                                                        title  \
country   province
Argentina Mendoza Province  Bodega Catena Zapata 2006 Nicasia Vineyard Mal...
          Other                            Colomé 2010 Reserva Malbec (Salta)
Armenia   Armenia                 Van Ardi 2015 Estate Bottled Rosé (Armenia)
Australia Australia Other   Marquis Philips 2000 Sarah's Blend Red (South ...
          New South Wales   De Bortoli 2007 Noble One Bortytis Semillon (N...
...                                                                       ...
Uruguay   Juanico           Familia Deicas 2004 Preludio Barrel Select Lot...
          Montevideo        Bouza 2015 Monte Vide Eu Tannat-Merlot-Tempran...
          Progreso          Pisano 2007 Etxe Oneko Fortified Sweet Red Tan...
          San Jose          Castillo Viejo 2005 El Preciado Gran Reserva R...
          Uruguay           Narbona NV Blend 002 Limited Edition Tannat-Ca...

                                          variety                winery
country   province
Argentina Mendoza Province                 Malbec  Bodega Catena Zapata
          Other                            Malbec                Colomé
Armenia   Armenia                            Rosé              Van Ardi
Australia Australia Other               Red Blend       Marquis Philips
          New South Wales                Sémillon            De Bortoli
...                                           ...                   ...
Uruguay   Juanico                       Red Blend        Familia Deicas
          Montevideo                    Red Blend                 Bouza
          Progreso                         Tannat                Pisano
          San Jose                      Red Blend        Castillo Viejo
          Uruguay           Tannat-Cabernet Franc               Narbona

[425 rows x 13 columns]

**Awesome!** contry, province에서 point가 가장 높은 와인 데이터를 추출했다

Another <code>groupby()</code>mehtod worth mentioning is <code>agg()</code>, which lets you run a bunch of different functions on your DataFrame simultaneously.<br>
For example, we can generate a simple statistical summary of the dataset as follows.

In [35]:
reviews.groupby(['country']).price.agg([len, min, max])

                            len   min     max
country
Argentina                3800.0   4.0   230.0
Armenia                     2.0  14.0    15.0
Australia                2329.0   5.0   850.0
Austria                  3345.0   7.0  1100.0
Bosnia and Herzegovina      2.0  12.0    13.0
Brazil                     52.0  10.0    60.0
Bulgaria                  141.0   8.0   100.0
Canada                    257.0  12.0   120.0
Chile                    4472.0   5.0   400.0
China                       1.0  18.0    18.0
Croatia                    73.0  12.0    65.0
Cyprus                     11.0  11.0    21.0
Czech Republic             12.0  15.0    45.0
Egypt                       1.0   NaN     NaN
England                    74.0  25.0    95.0
France                  22093.0   5.0  3300.0
Georgia                    86.0   9.0    40.0
Germany                  2165.0   5.0   775.0
Greece                    466.0   8.0    79.0
Hungary                   146.0  10.0   764.0
India                       9.0  10.0    20.0
Israel                    505.0   8.0   150.0
Italy                   19540.0   5.0   900.0
Lebanon                    35.0  13.0    75.0
Luxembourg                  6.0  16.0    30.0
Macedonia                  12.0  15.0    20.0
Mexico                     70.0   8.0   108.0
Moldova                    59.0   8.0    42.0
Morocco                    28.0  14.0    40.0
New Zealand              1419.0   7.0   130.0
Peru                       16.0  10.0    68.0
Portugal                 5691.0   5.0  1000.0
Romania                   120.0   4.0   320.0
Serbia                     12.0  15.0    42.0
Slovakia                    1.0  16.0    16.0
Slovenia                   87.0   7.0    90.0
South Africa             1401.0   5.0   330.0
Spain                    6645.0   4.0   770.0
Switzerland                 7.0  21.0   160.0
Turkey                     90.0  14.0   120.0
US                      54504.0   4.0  2013.0
Ukraine                    14.0   6.0    13.0
Uruguay                   109.0  10.0   130.0

In [46]:
reviews.groupby('country').points.agg(['mean', 'std', max, min])

                             mean       std  max  min
country
Argentina               86.710263  3.179627   97   80
Armenia                 87.500000  0.707107   88   87
Australia               88.580507  2.989900  100   80
Austria                 90.101345  2.499799   98   82
Bosnia and Herzegovina  86.500000  2.121320   88   85
Brazil                  84.673077  2.340782   89   80
Bulgaria                87.936170  2.077817   91   80
Canada                  89.369650  2.384752   94   82
Chile                   86.493515  2.692959   95   80
China                   89.000000       NaN   89   89
Croatia                 87.219178  2.399344   91   81
Cyprus                  87.181818  1.601136   89   85
Czech Republic          87.250000  1.712255   89   84
Egypt                   84.000000       NaN   84   84
England                 91.581081  1.843216   95   89
France                  88.845109  3.044423  100   80
Georgia                 87.686047  2.087845   92   82
Germany                 89.851732  2.469351   98   81
Greece                  87.283262  2.185293   93   82
Hungary                 89.191781  2.686659   97   81
India                   90.222222  1.715938   93   87
Israel                  88.471287  2.478412   94   80
Italy                   88.562231  2.649756  100   80
Lebanon                 87.685714  2.784109   91   82
Luxembourg              88.666667  0.816497   90   88
Macedonia               86.833333  1.749459   89   84
Mexico                  85.257143  2.722348   92   80
Moldova                 87.203390  2.419601   91   82
Morocco                 88.571429  1.687175   93   85
New Zealand             88.303030  2.435008   95   80
Peru                    83.562500  1.860779   86   80
Portugal                88.250220  2.996122  100   80
Romania                 86.400000  1.716945   92   82
Serbia                  87.500000  1.314257   89   86
Slovakia                87.000000       NaN   87   87
Slovenia                88.068966  1.730661   92   82
South Africa            88.056388  2.435826   95   82
Spain                   87.288337  3.066284   98   80
Switzerland             88.571429  2.507133   90   83
Turkey                  88.088889  1.975379   92   84
US                      88.563720  3.114840  100   80
Ukraine                 84.071429  1.591530   88   82
Uruguay                 86.752294  2.687957   92   80

In [42]:
reviews.groupby('country').points.agg(['mean', max, min]).idxmax()

mean      England
max     Australia
min         China
dtype: object

In [52]:
reviews.groupby('country').points.agg(['mean', 'std'])

                             mean       std
country
Argentina               86.710263  3.179627
Armenia                 87.500000  0.707107
Australia               88.580507  2.989900
Austria                 90.101345  2.499799
Bosnia and Herzegovina  86.500000  2.121320
Brazil                  84.673077  2.340782
Bulgaria                87.936170  2.077817
Canada                  89.369650  2.384752
Chile                   86.493515  2.692959
China                   89.000000       NaN
Croatia                 87.219178  2.399344
Cyprus                  87.181818  1.601136
Czech Republic          87.250000  1.712255
Egypt                   84.000000       NaN
England                 91.581081  1.843216
France                  88.845109  3.044423
Georgia                 87.686047  2.087845
Germany                 89.851732  2.469351
Greece                  87.283262  2.185293
Hungary                 89.191781  2.686659
India                   90.222222  1.715938
Israel                  88.471287  2.478412
Italy                   88.562231  2.649756
Lebanon                 87.685714  2.784109
Luxembourg              88.666667  0.816497
Macedonia               86.833333  1.749459
Mexico                  85.257143  2.722348
Moldova                 87.203390  2.419601
Morocco                 88.571429  1.687175
New Zealand             88.303030  2.435008
Peru                    83.562500  1.860779
Portugal                88.250220  2.996122
Romania                 86.400000  1.716945
Serbia                  87.500000  1.314257
Slovakia                87.000000       NaN
Slovenia                88.068966  1.730661
South Africa            88.056388  2.435826
Spain                   87.288337  3.066284
Switzerland             88.571429  2.507133
Turkey                  88.088889  1.975379
US                      88.563720  3.114840
Ukraine                 84.071429  1.591530
Uruguay                 86.752294  2.687957

In [60]:
reviews.groupby('country').points.agg(['mean', 'std'])['mean'].idxmax()

'England'

In [63]:
high_point_country = reviews.groupby('country').points.agg(['mean', 'std'])
# high_point_country
high_point_country['mean std'] = 0
high_point_country['mean std'] = high_point_country['mean'] - high_point_country['std']
high_point_country['mean std'].idxmax()

'England'

In [64]:
high_point_country

                             mean       std   mean std
country
Argentina               86.710263  3.179627  83.530636
Armenia                 87.500000  0.707107  86.792893
Australia               88.580507  2.989900  85.590607
Austria                 90.101345  2.499799  87.601546
Bosnia and Herzegovina  86.500000  2.121320  84.378680
Brazil                  84.673077  2.340782  82.332295
Bulgaria                87.936170  2.077817  85.858353
Canada                  89.369650  2.384752  86.984897
Chile                   86.493515  2.692959  83.800556
China                   89.000000       NaN        NaN
Croatia                 87.219178  2.399344  84.819835
Cyprus                  87.181818  1.601136  85.580682
Czech Republic          87.250000  1.712255  85.537745
Egypt                   84.000000       NaN        NaN
England                 91.581081  1.843216  89.737865
France                  88.845109  3.044423  85.800686
Georgia                 87.686047  2.087845  85.598201
Germany                 89.851732  2.469351  87.382382
Greece                  87.283262  2.185293  85.097969
Hungary                 89.191781  2.686659  86.505121
India                   90.222222  1.715938  88.506284
Israel                  88.471287  2.478412  85.992875
Italy                   88.562231  2.649756  85.912476
Lebanon                 87.685714  2.784109  84.901606
Luxembourg              88.666667  0.816497  87.850170
Macedonia               86.833333  1.749459  85.083875
Mexico                  85.257143  2.722348  82.534795
Moldova                 87.203390  2.419601  84.783788
Morocco                 88.571429  1.687175  86.884253
New Zealand             88.303030  2.435008  85.868022
Peru                    83.562500  1.860779  81.701721
Portugal                88.250220  2.996122  85.254098
Romania                 86.400000  1.716945  84.683055
Serbia                  87.500000  1.314257  86.185743
Slovakia                87.000000       NaN        NaN
Slovenia                88.068966  1.730661  86.338304
South Africa            88.056388  2.435826  85.620563
Spain                   87.288337  3.066284  84.222053
Switzerland             88.571429  2.507133  86.064296
Turkey                  88.088889  1.975379  86.113510
US                      88.563720  3.114840  85.448880
Ukraine                 84.071429  1.591530  82.479899
Uruguay                 86.752294  2.687957  84.064337

China...lol...

## Multi-indexes

In [67]:
countries_reviewed = reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                             len
country   province
Argentina Mendoza Province  3264
          Other              536
Armenia   Armenia              2
Australia Australia Other    245
          New South Wales     85
...                          ...
Uruguay   Juanico             12
          Montevideo          11
          Progreso            11
          San Jose             3
          Uruguay             24

[425 rows x 1 columns]

In [69]:
mi = countries_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In general the multi-index method you'll use most often is the one for converting back to a regular index<br>

<code>reset_index()</code>

In [72]:
countries_reviewed.reset_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

## Sorting

To get data in the order want in, we can sort it ourselves<br>

the <code>sort_values()</code> mehtod is handy for this.

In [73]:
countries_reviewed = countries_reviewed.reset_index() # .reset_index()
countries_reviewed.sort_values(by='len')

          country               province    len
179        Greece  Muscat of Kefallonian      1
192        Greece          Sterea Ellada      1
194        Greece                 Thraki      1
354  South Africa             Paardeberg      1
40         Brazil       Serra do Sudeste      1
..            ...                    ...    ...
409            US                 Oregon   5373
227         Italy                Tuscany   5897
118        France               Bordeaux   5941
415            US             Washington   8639
392            US             California  36247

[425 rows x 3 columns]

<code>sort_values()</code> defaults to an ascending sort, where the lowest values go first. However, most of the time we want a descending sort, where the higher numbers go first. That goes thusly

In [75]:
countries_reviewed.sort_values(by='len', ascending=False)

          country         province    len
392            US       California  36247
415            US       Washington   8639
118        France         Bordeaux   5941
227         Italy          Tuscany   5897
409            US           Oregon   5373
..            ...              ...    ...
101       Croatia              Krk      1
247   New Zealand        Gladstone      1
357  South Africa  Piekenierskloof      1
63          Chile          Coelemu      1
149        Greece           Beotia      1

[425 rows x 3 columns]

To sort by index values, use the companion method <code>sort_index()</code>. <br>
This method has the same arguments and default order:

In [77]:
countries_reviewed.sort_index()

       country          province   len
0    Argentina  Mendoza Province  3264
1    Argentina             Other   536
2      Armenia           Armenia     2
3    Australia   Australia Other   245
4    Australia   New South Wales    85
..         ...               ...   ...
420    Uruguay           Juanico    12
421    Uruguay        Montevideo    11
422    Uruguay          Progreso    11
423    Uruguay          San Jose     3
424    Uruguay           Uruguay    24

[425 rows x 3 columns]

In [ ]:
countries_reviewed.sort_values(by=['country', 'len'])

# Exercises

## 1.
Who are the most common wine reviewers in the dataset? Create a `Series` whose index is the `taster_twitter_handle` category from the dataset, and whose values count how many reviews each person wrote.

In [ ]:
#q1.hint()
#q1.solution()

## 2.
What is the best wine I can buy for a given amount of money? Create a `Series` whose index is wine prices and whose values is the maximum number of points a wine costing that much was given in a review. Sort the values by price, ascending (so that `4.0` dollars is at the top and `3300.0` dollars is at the bottom).

In [ ]:
best_rating_per_price = ____

# Check your answer
q2.check()

In [ ]:
#q2.hint()
#q2.solution()

## 3.
What are the minimum and maximum prices for each `variety` of wine? Create a `DataFrame` whose index is the `variety` category from the dataset and whose values are the `min` and `max` values thereof.

In [ ]:
price_extremes = ____

# Check your answer
q3.check()

In [ ]:
#q3.hint()
#q3.solution()

## 4.
What are the most expensive wine varieties? Create a variable `sorted_varieties` containing a copy of the dataframe from the previous question where varieties are sorted in descending order based on minimum price, then on maximum price (to break ties).

In [ ]:
sorted_varieties = ____

# Check your answer
q4.check()

In [ ]:
#q4.hint()
#q4.solution()

## 5.
Create a `Series` whose index is reviewers and whose values is the average review score given out by that reviewer. Hint: you will need the `taster_name` and `points` columns.

In [ ]:
reviewer_mean_ratings = ____

# Check your answer
q5.check()

In [ ]:
#q5.hint()
#q5.solution()

Are there significant differences in the average scores assigned by the various reviewers? Run the cell below to use the `describe()` method to see a summary of the range of values.

In [ ]:
reviewer_mean_ratings.describe()

## 6.
What combination of countries and varieties are most common? Create a `Series` whose index is a `MultiIndex`of `{country, variety}` pairs. For example, a pinot noir produced in the US should map to `{"US", "Pinot Noir"}`. Sort the values in the `Series` in descending order based on wine count.

In [ ]:
country_variety_counts = ____

# Check your answer
q6.check()

In [ ]:
#q6.hint()
#q6.solution()

# Keep going

Move on to the [**data types and missing data**](https://www.kaggle.com/residentmario/data-types-and-missing-values).

---
**[Pandas Home Page](https://www.kaggle.com/learn/pandas)**





*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum) to chat with other Learners.*