**[Pandas Home Page](https://www.kaggle.com/learn/pandas)**

---

# Introduction

The first step in most data analytics projects is reading the data file. In this exercise, you'll create Series and DataFrame objects, both by hand and by reading data files.

Run the code cell below to load libraries you will need (including code to check your answers).

In [1]:
import pandas as pd
pd.set_option('max_rows', 5)
from learntools.core import binder; binder.bind(globals())
from learntools.pandas.creating_reading_and_writing import *
print("Setup complete.")

Setup complete.

# Exercises

## 1.

In the cell below, create a DataFrame `fruits` that looks like this:

![](https://i.imgur.com/Ax3pp2A.png)

In [4]:
df = pd.DataFrame([[30, 21]], columns=['Apple', 'Banana'])
df

   Apple  Banana
0     30      21

막상 코테를 시작하면 머리가 멍 ~ 해질수 있다는 말씀! 정말 다행인건! Documentation의 도움을 받을 수 있다는 것이지!

기본을 단단히 다진다는 마음으로 다시 한 번 해보자!(이번이 거의 5번째일듯!)

In [8]:
# First, Dictionary
df = pd.DataFrame({"Apple": [30], "Banana": [21]})
df

   Apple  Banana
0     30      21

In [9]:
df = pd.DataFrame({"Apple": [30, 21, 50], "Bananas": [20, 60, 80]})
df

   Apple  Bananas
0     30       20
1     21       60
2     50       80

In [11]:
# Second, Constructing DataFrame from numpy ndarray:
df = pd.DataFrame([[30, 21]],
                 columns = ['Apple', 'Bananas'])
df

   Apple  Bananas
0     30       21

In [12]:
df = pd.DataFrame([[30, 20],
                   [21, 60],
                   [50, 80]],
                 columns = ['Apple', 'Bananas'])
df

   Apple  Bananas
0     30       20
1     21       60
2     50       80

In [21]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruits.
fruits = pd.DataFrame({'Apples': [30], 'Bananas': [21]})

# Check your answer
q1.check()

Correct

In [ ]:
# q1.hint()
# q1.solution()

## 2.

Create a dataframe `fruit_sales` that matches the diagram below:

![](https://i.imgur.com/CHPn7ZF.png)

In [24]:
# Do it by myself!
fruit_sales = pd.DataFrame({'Apples': [35, 41], 'Bananas': [21, 34]},
                           index = ['2017 Sales', '2018 Sales'])
fruit_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [25]:
q2.check()

Correct

In [ ]:
# Your code goes here. Create a dataframe matching the above diagram and assign it to the variable fruit_sales.
fruit_sales = pd.DataFrame({'Apples': [35, 41], 'Bananas': [21, 34]},
#                           index={'2017 Sales', '2018 Sales'}
# Dictionary는 순서를 정할 수 없다!
                          index=['2017 Sales', '2018 Sales'])

fruit_sales = pd.DataFrame({'Apples':[35, 41], 'Bananas':[21,34]},
                          index=['2017 Sales', '2018 Sales'])

# Check your answer
q2.check()
fruit_sales

In [ ]:
# q2.hint()
# q2.solution()

## 3.

Create a variable `ingredients` with a Series that looks like:

```
Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: object
```

In [28]:
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'], dtype=object,
                       index=['Flour', 'Milk', 'Eggs', 'Spam'], name = 'Dinner')
ingredients

q3.check()

Correct

In [ ]:
'''
ingredients = pd.Series({'Flour': '4 cups', 'Milk': '1 cup', 'Eggs': '2 large', 
                        'Spam': '1 can'},
                       name='Dinner')
'''
ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'],
                        index=['Flour', 'Milk', 'Eggs', 'Spam'],
                       name='Dinner')

ingredients = pd.Series(['4 cups', '1 cup', '2 large', '1 can'],
                       index = ['Flour', 'Milk', 'Eggs', 'Spam'],
                       name='Dinner')

# Check your answer
q3.check()
ingredients

In [29]:
#q3.hint()
#q3.solution()

오... 다시보기 정말 잘했다... 왜이리 새로운지...ㅋㅋ

## 4.

Read the following csv dataset of wine reviews into a DataFrame called `reviews`:

![](https://i.imgur.com/74RCZtU.png)

The filepath to the csv file is `../input/wine-reviews/winemag-data_first150k.csv`. The first few lines look like:

```
,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,"This tremendous 100% varietal wine[...]",Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and[...]",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,,Tinta de Toro,Bodega Carmen Rodríguez
```

In [37]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv',  index_col=0 ) # index_col: 문자열 이름 또는 열 인덱스로 제공되는 DataFrame의 행레이블로 사용할 열이다.
                                                                                         # index_col = 0을 많이 사용하게 될 것 같은 느낌?
# q4.check()
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [39]:
q4.check()

Correct

In [42]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv', index_col=False)
reviews.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [ ]:
reviews = pd.read_csv('../input/wine-reviews/winemag-data_first150k.csv', index_col=0)

# Check your answer
q4.check()
reviews

In [33]:
# q4.hint()
q4.solution()

Hint: Note that the csv file begins with an unnamed column of increasing integers. We want this to be used as the index. Check out the description of the `index_col` keyword argument in [the docs for `read_csv`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).

## 5.

Run the cell below to create and display a DataFrame called `animals`:

In [43]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In the cell below, write code to save this DataFrame to disk as a csv file with the name `cows_and_goats.csv`.

In [44]:
animals = pd.DataFrame({'Cows':[12, 20], 'Goats':[22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [46]:
animals.to_csv('./cows_and_goats.csv')
q5.check()

Correct

In [ ]:
# Your code goes here

# pandas.DataFrame.to_csv()
# animals.to_csv('./cows_and_goats.csv')
animals.to_csv('./cows_and_goats.csv')


# Check your answer
q5.check()

In [47]:
#q5.hint()
#q5.solution()

## Summary
* DataFrame을 생성하는 것부터 시작!
    * Dictionary와 같이 생성하는 방법
    * Numpy array와 같이 생성하는 방법
* Series 생성
* 파일을 불러오는 방법 및 저장하는 방법
    * <code>pd.read_csv()</code>
        * Unnamed:0를 row의 열로 사용하고 싶다면??: index_col=0
    * <code>df.to_csv()</code>

# Keep going

Move on to learn about **[indexing, selecting and assigning](https://www.kaggle.com/residentmario/indexing-selecting-assigning)**.

---
**[Pandas Home Page](https://www.kaggle.com/learn/pandas)**





*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum) to chat with other Learners.*